<?php
/**
 * This is a generic mail template.
 *
 * @author     Philipp Frischmuth <pfrischmuth@googlemail.com>
 * @copyright  Copyright (c) 2010, {@link http://aksw.org AKSW}
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>

<div style="margin-left:auto; margin-right: auto; width: 695px; height: 20px; background-color: <?php echo $this->highlightColor; ?>; border: 1px solid <?php echo $this->highlightColor; ?>; color: #fff; font-weight: bold; padding: 5px 0 0 5px"><?php echo $this->senderName; ?>
</div>
<div style="margin-left: auto; margin-right: auto; border-left: 1px solid #ccc; border-right: 1px solid #ccc; border-bottom: 1px solid #ccc; padding: 20px; width: 660px; font-familiy: sans-serif;">
  <?php echo $this->hi; ?>
  <br /><br />
  <?php if (isset($this->sourcePubInfo['name'])): ?>
    <?php echo $this->sourcePubInfo['name']; ?>
  <?php else: ?>
    someone
  <?php endif; ?>
    added a 
  <?php if (isset($this->relInfo['title'])): ?>
    <a href="<?php echo $this->relInfo['uri']; ?>" style="text-decoration: none; font-weight: bold; color: <?php echo $this->linkColor; ?>"><?php echo $this->relInfo['title']; ?></a>
  <?php else: ?>
    <a href="<?php echo $this->relInfo['uri']; ?>" style="text-decoration: none; font-weight: bold; color: <?php echo $this->linkColor; ?>">new</a>
  <?php endif; ?>
     link to 
  <?php if (isset($this->targetInfo['title'])): ?>
    your resource <a href="<?php echo $this->targetInfo['uri']; ?>" style="text-decoration: none; font-weight: bold; color: <?php echo $this->linkColor; ?>"><?php echo $this->targetInfo['title']; ?></a>.
  <?php else: ?>
    one of your resources.
  <?php endif; ?>
  <br />
  <?php if (isset($this->sourceInfo['title'])): ?>
    <a href="<?php echo $this->sourceInfo['uri']; ?>" style="text-decoration: none; font-weight: bold; color: <?php echo $this->linkColor; ?>"><?php echo $this->sourceInfo['title']; ?></a> is the resource that contains the link.
  <?php elseif (isset($this->sourceInfo['uri'])): ?>
    You can view the resource containing the link by clicking on the following link: <a href="<?php echo $this->sourceInfo['uri']; ?>" style="text-decoration: none; font-weight: bold; color: <?php echo $this->linkColor; ?>">Source Resource</a>
  <?php endif; ?>
  <br />
  
  <?php if (isset($this->comment)): ?>
  Comment: <?php echo $this->comment; ?><br />
  <?php endif; ?>
  <div style="padding: 10px; margin: 20px 10px 20px 10px; border-top: 1px solid #ccc; border-bottom: 1px solid #ccc">
    <span>Info about the publisher of the source resource:</span>
    <br />
    <div style="margin: 10px 0 0 0;">
      <?php if (isset($this->sourcePubInfo['depiction'])): ?>
        <img src="<?php echo $this->sourcePubInfo['depiction']; ?>" style="margin-right: 10px;" />
      <?php endif; ?>
      <?php if (isset($this->sourcePubInfo['name'])): ?>
        <a href="<?php echo $this->sourcePubInfo['uri']; ?>" style="text-decoration: none; font-weight: bold; color: <?php echo $this->linkColor; ?>; vertical-align: top;"><?php echo $this->sourcePubInfo['name']; ?></a>
      <?php endif; ?>
    </div>
  </div>
  <?php echo $this->bye; ?>

  <div>

      PS: Here are the web addresses (URIs) of all involved resources:
      subject:   <?php echo $this->sourceInfo['uri']; ?>
      predicate: <?php echo $this->relInfo['uri']; ?>
      object:    <?php echo $this->targetInfo['uri']; ?>
  </div>
</div>
